#!/usr/bin/env python3
"""
Generates PNG fixtures for png.spec.ts using Pillow as an INDEPENDENT oracle,
plus ImageMagick for the one thing Pillow's encoder cannot produce
(Adam7 interlacing - PIL always writes IHDR interlace=0).

Run from anywhere:  python3 test/fixtures/make-fixtures.py

Each *.png fixture gets a matching *.expected.json written by asking Pillow
to re-open the file it just wrote and report what it sees. The decoder tests
compare against these JSON files, never against this script's in-memory
arrays, so the oracle is genuinely external to the TypeScript decoder.
"""
import json
import os
import subprocess
import sys

import warnings

warnings.filterwarnings("ignore", category=DeprecationWarning)

from PIL import Image

FIXTURES_DIR = os.path.dirname(os.path.abspath(__file__))


def write_expected(png_path, palette=None):
    """Re-open the just-written PNG with PIL and dump ground truth."""
    im = Image.open(png_path)
    im.load()
    expected = {
        "width": im.width,
        "height": im.height,
        "mode": im.mode,
    }
    if im.mode == "P":
        indices = list(im.getdata())
        raw_palette = im.getpalette() or []
        num_colors = len(raw_palette) // 3
        pal = []
        transparency = im.info.get("transparency")
        for i in range(num_colors):
            r = raw_palette[i * 3]
            g = raw_palette[i * 3 + 1]
            b = raw_palette[i * 3 + 2]
            if isinstance(transparency, (bytes, bytearray)):
                a = transparency[i] if i < len(transparency) else 255
            else:
                a = 255
            pal.append([r, g, b, a])
        expected["indices"] = indices
        expected["palette"] = pal
    else:
        rgba = im.convert("RGBA")
        pixels = list(rgba.getdata())
        expected["rgba"] = [c for px in pixels for c in px]
    out_path = png_path[:-4] + ".expected.json"
    with open(out_path, "w") as f:
        json.dump(expected, f)
    print(f"  wrote {os.path.basename(out_path)}")


def make_indexed8_trns():
    """8-bit indexed, 20-colour palette, tRNS array SHORTER than the palette."""
    path = os.path.join(FIXTURES_DIR, "indexed8-trns.png")
    w, h = 32, 24
    im = Image.new("P", (w, h))
    palette = []
    for i in range(20):
        palette.extend([(i * 13) % 256, (i * 47) % 256, (i * 91) % 256])
    im.putpalette(palette)
    data = bytes([(x + y * 3) % 20 for y in range(h) for x in range(w)])
    im.putdata(list(data))
    # Only the first 10 palette entries get an explicit alpha; entries
    # 10..19 must decode as 255 (the "missing entries are 255" case).
    trns = bytes([(i * 25) % 256 for i in range(10)])
    im.save(path, transparency=trns)
    print(f"wrote {os.path.basename(path)}")
    write_expected(path)


def make_indexed4():
    """4-bit indexed, 10-colour palette."""
    path = os.path.join(FIXTURES_DIR, "indexed4.png")
    w, h = 17, 13  # deliberately non-byte-aligned width
    im = Image.new("P", (w, h))
    palette = []
    for i in range(10):
        palette.extend([(i * 23) % 256, (i * 61) % 256, (i * 5) % 256])
    im.putpalette(palette)
    data = bytes([(x * 3 + y) % 10 for y in range(h) for x in range(w)])
    im.putdata(list(data))
    im.save(path)
    print(f"wrote {os.path.basename(path)}")
    write_expected(path)


def make_indexed1():
    """1-bit indexed, 2-colour palette."""
    path = os.path.join(FIXTURES_DIR, "indexed1.png")
    w, h = 9, 7  # non-byte-aligned width to exercise sub-byte row packing
    im = Image.new("P", (w, h))
    palette = [10, 20, 30, 240, 230, 220]
    im.putpalette(palette)
    data = bytes([(x + y) % 2 for y in range(h) for x in range(w)])
    im.putdata(list(data))
    im.save(path)
    print(f"wrote {os.path.basename(path)}")
    write_expected(path)


def make_truecolor_rgba_gradient():
    """
    RGBA truecolour gradient, sized/patterned so Pillow's adaptive filter
    picker will choose more than one filter type across scanlines - this is
    the fixture the Paeth-predictor test exercises. Verified after writing
    that filter bytes 0-4 are not all identical (see verify_multi_filter).
    """
    path = os.path.join(FIXTURES_DIR, "truecolor-rgba.png")
    w, h = 48, 40
    im = Image.new("RGBA", (w, h))
    px = im.load()
    for y in range(h):
        for x in range(w):
            r = (x * 255) // (w - 1)
            g = (y * 255) // (h - 1)
            b = (x ^ y) & 0xFF
            a = 255 if (x + y) % 7 else (x * 3) % 256
            px[x, y] = (r, g, b, a)
    im.save(path)
    print(f"wrote {os.path.basename(path)}")
    write_expected(path)


def make_interlaced():
    """
    Adam7-interlaced PNG for the REJECTION test. Pillow cannot write
    interlace=1 (its encoder hardcodes the IHDR interlace byte to 0), so this
    one fixture is generated by ImageMagick instead.
    """
    path = os.path.join(FIXTURES_DIR, "interlaced.png")
    src = os.path.join(FIXTURES_DIR, "truecolor-rgba.png")
    if not os.path.exists(src):
        make_truecolor_rgba_gradient()
    result = subprocess.run(
        ["magick", src, "-interlace", "PNG", path],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        result = subprocess.run(
            ["convert", src, "-interlace", "PNG", path],
            capture_output=True,
            text=True,
        )
    if result.returncode != 0:
        print("ERROR: neither `magick` nor `convert` produced the interlaced fixture",
              file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)
    print(f"wrote {os.path.basename(path)} (via ImageMagick, interlace method 1)")
    # No .expected.json for this one - the test only asserts rejection.


def verify_multi_filter(path):
    """Sanity-check: parse the fixture's own filter bytes and assert >1 kind."""
    import struct
    import zlib

    with open(path, "rb") as f:
        raw = f.read()
    assert raw[:8] == b"\x89PNG\r\n\x1a\n"
    pos = 8
    width = height = bit_depth = color_type = None
    idat = b""
    while pos < len(raw):
        length = struct.unpack(">I", raw[pos:pos + 4])[0]
        ctype = raw[pos + 4:pos + 8]
        data = raw[pos + 8:pos + 8 + length]
        if ctype == b"IHDR":
            width, height, bit_depth, color_type = struct.unpack(">IIBB", data[:10])
        elif ctype == b"IDAT":
            idat += data
        elif ctype == b"IEND":
            break
        pos += 8 + length + 4
    raw_scan = zlib.decompress(idat)
    bpp = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[color_type]
    if bit_depth < 8:
        bytes_per_pixel_group = 1
    else:
        bytes_per_pixel_group = bpp * (bit_depth // 8)
    row_bytes = (width * bpp * bit_depth + 7) // 8
    stride = row_bytes + 1
    filters_seen = set()
    for y in range(height):
        filters_seen.add(raw_scan[y * stride])
    assert len(filters_seen) > 1, (
        f"fixture {path} only used filter types {filters_seen}; "
        "the Paeth test needs a fixture PIL actually varied. Adjust the "
        "gradient pattern in make_truecolor_rgba_gradient()."
    )
    print(f"  {os.path.basename(path)} uses filter types {sorted(filters_seen)}")


def main():
    make_indexed8_trns()
    make_indexed4()
    make_indexed1()
    make_truecolor_rgba_gradient()
    verify_multi_filter(os.path.join(FIXTURES_DIR, "truecolor-rgba.png"))
    make_interlaced()
    print("done")


if __name__ == "__main__":
    main()
